name: Context


on:
 workflow_dispatch

jobs:
 echo-info:
  runs-on: ubuntu-latest
  steps:
   - name: Display Info
     run: |
      echo "event name is ${{github.event_name}}"
      echo "ref is ${{github.ref}}"
      echo "SHA value is ${{github.sha}}"
      echo "Actor is ${{github.actor}}"
      echo "Workflow name is ${{github.workflow}}"
      echo "Run Id is ${{github.run_id}}"
      echo "Run  number is ${{github.run_number}}"
      
      
