name: First Workflow

on:

  

jobs:
 code-checkout:
  runs-on: ubuntu-latest 
  steps:
   - name: Code checkout  # GITHUB_WORKSPACE 
     uses: actions/checkout@v4.2.2
   - name: Print 
     run: echo ' first workflow'


 
