name: Github Context


on:
 workflow_dispatch
env:
 USERNAME: ${{vars.USERNAME}}
 PASSWORD: ${{secrets.PASSWORD}}

jobs:
 echo-info:
  runs-on: ubuntu-latest
  steps:
   - name: Display Info
     run: |
      echo "event name is ${{github.event_name}}"
      echo "ref is ${{github.ref}}"
      echo "SHA value is ${{github.sha}}"
      echo "Actor is ${{github.actor}}"
      echo "Workflow name is ${{github.workflow}}"
      echo "Run Id is ${{github.run_id}}"
      echo "Run  number is ${{github.run_number}}"
 build: 
 
 call-deploy:
  if: github.ref_name == "/.github/workflows/deploy.yml"
  runs-on: ubuntu-latest
  steps:
   - run: echo " Run only if event is pull request"
 test:
  if: github.event_name == 'pull_request"
  runs-on: ubuntu-latest
  steps:
   - run: echo " Run only if event is pull request"
 deploy:
  if: github.ref == "refs/heads/master"
  runs-on: ubuntu-latest
  steps: 
   - run: echo "Deploy the job only if condition passes"
 check-branch:
  runs-on: ubuntu-latest
  steps:
   - run: |
      if [[ "${{Github.ref}}"  == "refs/heads/master"]]; then
       echo " deploy in master"
      else
       echo " deploy in  another branch"
      fi


      
